name = "alirezaPN"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
u = "c6b66fec-b8f1-4756-8351-491b8f7ebe0e"
 
[[kv_namespaces]] 
binding = "C" 
id = "cabc92ca084f4dd6b832b13e731e2d9a" 
