name = "mozpn-worker"
main = "dist/MozPN-obfuscated.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
u = "55e489b6-fd10-4ba8-a769-b7b010f7f7e5"
 
[[kv_namespaces]] 
binding = "C" 
id = "eb170c483bfc4bbd925434e19cb3150b" 
